### ISSUE TITLE
Canonical T-Res resources

### ISSUE THREAD

**Issue by thobson88** [Living-with-machines/T-Res#278]
The `resources/` subdirectory is .gitignored due to the large size of the data files on which T-Res depends, but there is currently no shared storage location containing a canonical set of resources.

This makes deployment more difficult and also causes problems with integration tests which depend on the resources and cannot be run with consistent results unless a common resources are used.

Steps:
 - [x] identify a canonical set of resources (on existing VMs/disks),
 - [x] collect these resources into a central storage location (with appropriate compression),
 - [x] write a script to automatically download & unpack them into the `resources/` subdirectory,
 - [x] separately include a subset of resources under the `tests/` subdirectory, for unit test fixtures,
 - [x] mark any tests depending on the full, canonical resources to be skipped by default when running pytest,
 - [x] repeat these steps for the `experiments/` subdirectory.

**Comment by thobson88** [comment]
### Identify a canonical set of resources

Latest and most complete resources (afaics) are to be found at: 
 - [`deployed-toponym-resolution`](https://portal.azure.com/#@turing.ac.uk/resource/subscriptions/b8871872-a5e3-473f-b9b9-f4baaab6a9a0/resourceGroups/toponym-resolution/providers/Microsoft.Compute/virtualMachines/deployed-toponym-resolution/overview) VM, under `/home/lukehare/T-Res/resources` 
 - [`toponymVM2.0`](https://portal.azure.com/#@turing.ac.uk/resource/subscriptions/b8871872-a5e3-473f-b9b9-f4baaab6a9a0/resourceGroups/toponym-resolution/providers/Microsoft.Compute/virtualMachines/toponymVM2.0/overview) under `/resources/home/mcollardanuy/toponym-resolution/resources`

**Comment by thobson88** [comment]
### Collect resources into a central storage location (with appropriate compression)

Script for bundling up the resources:
```bash
#!/bin/bash

# Script that creates a zip file of T-Res resources.

# Run this script from the resources/ directory and pass the output directory
# in which the file `resources.zip` will be created.

zip "$1/resources.zip" publication_metadata.json
zip -ur "$1/resources.zip" deezymatch/
zip -ur "$1/resources.zip" models/
zip -ur "$1/resources.zip" rel_db/
zip -ur "$1/resources.zip" wikidata/
zip -ur "$1/resources.zip" wikipedia/
echo "Created T-Res resources.zip at $1/resources.zip"
```

To be run from `/home/lukehare/T-Res/resources` on the `deployed-toponym-resolution` VM.

Note: this script takes several minutes to run because some subfolders contain many small files (e.g. `deezymatch/candidate_vectors/wkdtalts_w2v_ocr/embeddings/`). It may be worth tweaking so that those subfolders are not compressed but instead added with level 0 compression. This would save time when uncompressing (at the expense of a large zip file).

Update: files now [on Azure](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2Fb8871872-a5e3-473f-b9b9-f4baaab6a9a0%2Fresourcegroups%2FT-Res%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Ftres/path/resources/etag/%220x8DCEE948328A6DC%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None) in `tres` storage account, `resources` container.

**Comment by thobson88** [comment]
With these resources in place (on Azure, at least), I'm now making sure all tests pass on Rosie's `dev_rw` branch, in preparation for merging [that PR](https://github.com/Living-with-machines/T-Res/pull/270).

**Comment by thobson88** [comment]
### Script to fetch resources from Azure

Added to the existing PR as `resources/fetch_resources.py`. Requires AzCopy and a valid SAS token.

This is a stop-gap solution intended for internal use, pending public release of the resource files #279.

**Comment by thobson88** [comment]
All tests now pass on a new checkout (of `dev_rw`) after running the script `fetch_resources.py` with the command:
```
python resources/fetch_resources.py
```

**Comment by rwood-97** [comment]
Just spoke to @fedenanni and he is happy with this
